/* o comando select
seleção projeçao e junção
*/

Select now() as DATA_HORA, 'Otávio Wolff' as PROFESSOR;

SELECT 'Otávio Wolff';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME FROM Cliente;

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM Cliente;