/* SELECAO, PROJECAO E JUNCAO*/

/* PROJECAO > É TUDO QUE VOCE QUER VER NA TELA (QUERY) */

SELECT NOW() AS DATA_ATUAL;

SELECT 2 + 2 AS SOMA;

SELECT 2 + 2, NOME, NOW() FROM CLIENTE;

-- SELECT NOME, SEXO, TIPO, TELEFONE, BAIRRO (O RESTO VAI SER ENSINADO)

/* SELECAO -> É UM SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS DE UMA TABELA*/
/* A CLAUSULA DE SELECAO É WHERE*/

SELECT NOME, SEXO, EMAIL /* PROJECAO */
FROM CLIENTE /* ORIGEM */
WHERE SEXO = 'F'; /* SELECAO */

SELECT NUMERO 
FROM TELEFONE
WHERE TIPO = 'CEL';