/*
DML - DATA MANIPULATION LANGUAGE
DDL - DATA DEFINITION LANGUAGE
DCL - DATA CONTROL LANGUAGE
TCL - TRANSACTION CONTROL LANGUAGE
*/


/* DML */
/* INSERT */
INSERT INTO CLIENTE (NULL,'PAULA','M', NULL,'77771235345')