/*
Comandos DDL DATA DEFINITION LANGUAGE
*/

/*
CREATE - CRIAÇÃO DE TABELAS
ALTER - ALTERAÇÃO DE TABELAS
DROP - DELEÇÃO DE TABELAS
*/

CREATE TABLE PRODUTO(
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(30) NOT NULL,
    PRECO INT(11),
    FRETE FLOAT(10,2) NOT NULL
);


/*
ALTER TABLE

ALTER TABLE O NOME DE UMA COLUNA
CHANGE ...
*/

ALTER TABLE PRODUTO 
CHANGE PRECO VALOR_UNITARIO INT(11) NOT NULL;
-- BOM PARA QUANDO PRECISAR ALTERAR O NOME

ALTER TABLE PRODUTO
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;
-- BOM PARA QUANDO PRECISAR ALTERAR APENAS O TIPO DO DADO

/*
ADICIONANDO COLUNAS
*/

ALTER TABLE PRODUTO
ADD PESO FLOAT(10,2) NOT NULL;
-- ADICIONA UMA COLUNA AO FINAL DA TABELA

ALTER TABLE PRODUTO
DROP COLUMN PESO;
-- DELETA A COLUNA PESO

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;
-- ADICIONA UMA COLUNA APOS A OUTRA COLUNA ESPECIFICADA

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
FIRST;
-- ADICIONA UMA COLUNA AO INICIO DA TABELA

