INSERT INTO CLIENTE 
VALUES(NULL,'João','M',NULL,'12332112323');
INSERT INTO CLIENTE 
VALUES(NULL,'Maria','F','maria@gmail.com','12332772323');
INSERT INTO CLIENTE 
VALUES(NULL,'Carlos','M','Carlos@gmail.com','12332166323');
INSERT INTO CLIENTE 
VALUES(NULL,'André','M','andre@gmail.com','12552112323');
INSERT INTO CLIENTE 
VALUES(NULL,'Daiana','F','daiana@gmail.com','12333112323');
INSERT INTO CLIENTE 
VALUES(NULL,'Pedro','M','pedro@gmail.com','12335512323');

UPDATE CLIENTE 
SET EMAIL = 'joao@gmail.com'
WHERE IDCLIENTE = 2;

DELETE FROM CLIENTE 
WHERE IDCLIENTE = 1;

SELECT IDCLIENTE, NOME, EMAIL FROM CLIENTE WHERE IDCLIENTE = 2;

-- INSERTS NO ENDEREÇO

DESC ENDERECO;

INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO DE SA','CENTRO','B. HORIZONTE','MG',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA 7','CENTRO','VITÓRIA','ES',5);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALMIRANTE','ZONA SUL','ARACRUZ','ES',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA DESEMBARGADOR','VALADARES','MUNIQUE','RJ',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA PEROLA','DALES','IGUAPORE','PE',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA MUMBICA','ZUMBIS','PALMARES','BA',7);


-- INSERTS NO TELEFONE

INSERT INTO TELEFONE VALUES (NULL,'CEL','9991-6966',2);
INSERT INTO TELEFONE VALUES (NULL,'CEL','9781-6966',3);
INSERT INTO TELEFONE VALUES (NULL,'CEL','9591-6966',4);
INSERT INTO TELEFONE VALUES (NULL,'RES','3222-6966',4);
INSERT INTO TELEFONE VALUES (NULL,'CEL','9341-6966',5);
INSERT INTO TELEFONE VALUES (NULL,'COM','9624-6966',6);
INSERT INTO TELEFONE VALUES (NULL,'CEL','9764-6966',7);

UPDATE TELEFONE
SET NUMERO = '9991-6966'
WHERE IDTELEFONE = 1;

UPDATE TELEFONE
SET NUMERO = '9781-6966'
WHERE IDTELEFONE = 2;

UPDATE TELEFONE
SET NUMERO = '9591-6966'
WHERE IDTELEFONE = 3;

UPDATE TELEFONE
SET NUMERO = '3222-6966'
WHERE IDTELEFONE = 4;

UPDATE TELEFONE
SET NUMERO = '9341-6966'
WHERE IDTELEFONE = 5;

UPDATE TELEFONE
SET NUMERO = '9624-6966'
WHERE IDTELEFONE = 6;

UPDATE TELEFONE
SET NUMERO = '9764-6966'
WHERE IDTELEFONE = 7;

DELETE FROM TELEFONE WHERE IDTELEFONE = 1;