CREATE TABLE AUTORIA_CLIENTE(
    IDAUIT INT PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT,
    NOME VARCHAR(30),
    DATA_INSERCAO TIMESTAMP
);

CREATE TABLE CLIENTE(
    IDAUIT INT PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT,
    NOME VARCHAR(30),
    DATA_INSERCAO TIMESTAMP
);

CREATE TRIGGER AUDIT_INSERT_CLIENTE
AFTER INSERT ON CLIENTE
FOR EACH ROW
BEGIN   
    INSERT INTO AUTORIA_CLIENTE (IDCLIENTE,NOME,DATA_INSERCAO)
    VALUES (NULL,NEW.IDCLIENTE, NEW.NOME, NOW());
END$


INSERT INTO CLIENTE (IDCLIENTE, NOME, DATA_INSERCAO) VALUES
(NULL, 1, 'Carlos Silva', NOW()),
(NULL, 2, 'Ana Pereira', NOW()),
(NULL, 3, 'João Souza', NOW()),
(NULL, 4, 'Maria Oliveira', NOW()),
(NULL, 5, 'Pedro Costa', NOW());
