-- Aula sobre Views

SELECT 
    C.NOME, 
    IFNULL(C.EMAIL,'----') AS  EMAIL, 
    E.ESTADO,
    T.NUMERO AS TELEFONE
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON CLIENTE.IDCLIENTE = E.ID_CLIENTE
    LEFT JOIN TELEFONE T
    ON CLIENTE.IDCLIENTE = T.ID_CLIENTE;

/* VIEW */

SELECT 
    C.NOME, 
    C.SEXO,
    C.EMAIL,
    T.TIPO,
    T.NUMERO AS TELEFONE,
    E.BAIRRO,
    E.CIDADE,
    E.ESTADO
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
    LEFT JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE;


-- O CREATE VIEW FAZ COM QUE VOCÊ DEIXE MAIS RÁPIDO UMA 

CREATE VIEW RELATORIO AS
SELECT 
    C.NOME, 
    C.SEXO,
    C.EMAIL,
    T.TIPO,
    T.NUMERO AS TELEFONE,
    E.BAIRRO,
    E.CIDADE,
    E.ESTADO
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
    LEFT JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE;

-- DESSA FORMA VOCÊ TERA UM ACESSO MAIS RÁPIDO AO USO DESSE RELATÓRIO
-- O INDICADO É FAZER ESSA VIEW TER UMA FORMA DE RECONHECER ELA 
-- ENTÃO UTILIZE SUFIXOS PARA DAR TRANSPARENCIA A VIEW 

-- EX:
CREATE VIEW V_RELATORIO AS
SELECT 
    C.NOME, 
    C.SEXO,
    C.EMAIL,
    T.TIPO,
    T.NUMERO AS TELEFONE,
    E.BAIRRO,
    E.CIDADE,
    E.ESTADO
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
    LEFT JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE;

-- AS VIEWS TAMBÉM APARECEM COMO SE FOSSEM TABELAS REGISTRADAS NOS BANCOS DE DADOS
+--------------------+
| Tables_in_comercio |
+--------------------+
| cliente            |
| endereco           |
| relatorio          |
| telefone           |
+--------------------+

-- PARA APAGAR UMA VIEW FAZ:
DROP VIEW RELATORIO;

-- VOCÊ TAMBÉM PODE UTILIZAR O IFNULL DENTRO DO VIEW
-- EX:
CREATE VIEW V_RELATORIO AS
SELECT 
    C.NOME, 
    C.SEXO,
    IFNULL(C.EMAIL, '----') AS EMAIL,
    T.TIPO,
    IFNULL(T.NUMERO, '----') AS NUMERO,
    E.BAIRRO,
    E.CIDADE,
    E.ESTADO
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
    LEFT JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE;


-- ESSE TIPO DE CONSULTO É LEVEMENTE MENOS PERFORMÁTICA 
-- NECESSÁRIO, MAS BOA PARA NEGÓCIOS MAIS PRÁTICOS


-- VOCÊ TAMBÉM É CAPAZ DE UTILIZAR A VIEW PARA FAZER CONSULTAS COM COLUNAS QUE EXISTEM DENTRO DELA

SELECT NOME, NUMERO, ESTADO
FROM V_RELATORIO;

+----------+----------+--------+
| NOME     | NUMERO   | ESTADO |
+----------+----------+--------+
| GIOVANA  | 68976565 | MG     |
| GIOVANA  | 99656675 | MG     |
| KARLA    | ----     | RJ     |
| DANIELE  | 33567765 | RJ     |
| DANIELE  | 88668786 | RJ     |
| DANIELE  | 55689654 | RJ     |
| LORENA   | 88687979 | RJ     |
| EDUARDO  | 88965676 | ES     |
| ANTONIO  | ----     | RJ     |
| ANTONIO  | 89966809 | PR     |
| ELAINE   | 88679978 | SP     |
| CARMEM   | 99655768 | PR     |
| ADRIANA  | 89955665 | SP     |
| JOICE    | 77455786 | RJ     |
| JOICE    | 89766554 | RJ     |
| JOAQUINA | 77755785 | RJ     |
| JOAQUINA | 44522578 | RJ     |
| JOZIENE  | ----     | RJ     |
+----------+----------+--------+
