/* UPDATE, INSERT E DELETE */

INSERT INTO V_RELATORIO VALUES(
    'ANDREIA', 'F', 'ANDREIA@GMAIL.COM.BR','CEL', '872547864', 'CENTRO', 'VITORIA', 'ES'
)

ERROR 1471 (HY000): The target table V_RELATORIO of the INSERT is not insertable-into

DELETE FROM V_RELATORIO WHERE NOME = 'JORGE';

ERROR 1288 (HY000): The target table V_RELATORIO of the DELETE is not updatable

-- OPERAÇÕES DE DML EM TABELAS DE VIEW COM MAIS COMPLEXIDADE (JOIN) TRAZEM O ERRO DO VIEW
-- INSERTS E DELETES EM VIEW NÃO SÃO ACEITOS, RETORNAM ERROS

UPDATE V_RELATORIO SET NOME = 'JORGE' WHERE NOME = 'JOSE';

ERROR 1288 (HY000): The target table V_RELATORIO of the UPDATE is not updatable

-- UPDATES SÃO ACEITOS EM VIEW
-- *obs PELO VISTO UPDATES NÃO SÃO ACEITOS EM VIEWS.

CREATE TABLE JOGADORES(
    IDJOGADOR INT,
    NOME VARCHAR(30),
    ESTADO CHAR(2)
);

INSERT INTO JOGADORES VALUES (1, 'GUERREIRO', 'ES');
INSERT INTO JOGADORES VALUES (2, 'GABIGOL', 'RJ');
INSERT INTO JOGADORES VALUES (3, 'GANSO', 'RS');
INSERT INTO JOGADORES VALUES (4, 'NENE', 'SP');
INSERT INTO JOGADORES VALUES (5, 'VAGNER', 'RS');


CREATE VIEW V_JOGADORES AS 
SELECT NOME, ESTADO
FROM JOGADORES;

SELECT * FROM V_JOGADORES;

-- TABELAS MENOS COMPLEXAS DÁ PARA SEREM FEITAS INSERT, DELETE E UPDATE

-- ATUALIZANDO UMA VIEW

CREATE OR REPLACE VIEW V_JOGADORES_ES AS
SELECT IDJOGADOR, NOME, ESTADO
FROM JOGADORES
WHERE ESTADO = 'ES';

-- NESSA NOVA VIEW APENAS OS JOGADORES DO ES VÃO APARECER